Add player animations
gavrilovmiroslav/dagger-relic pull request #10
Opened 2023-04-03 17:38 UTC by abosiljcic

Player can run and stand. When the game starts the player is standing by default. When the left/right arrows are clicked, the player runs. These features are added to the struct MovementControlSystem in Main.cpp.

2023-04-04 19:42 UTC, gavrilovmiroslav requested changes

2023-04-04 19:42 UTC, gavrilovmiroslav commented on src/Main.cpp
> +	geometry::Vec2 velocitymax;
`velocity_max` and `move_force` plez

2023-04-04 19:42 UTC, gavrilovmiroslav commented on src/Main.cpp
> +static float fsignf(float x)
Could we put all of these functions into a header? Also, why are these all `static`?

2023-04-04 19:42 UTC, gavrilovmiroslav commented on src/Main.cpp
> +		for (auto&& [entity, keybinding, movement, sprite] : access_storage().each())
I'd also like `key_binding`; whenever you have multiple words, basically, cut it up

2023-04-05 16:58 UTC, Mentathiel requested changes

2023-04-05 16:58 UTC, Mentathiel commented on src/Main.cpp
> +		if (keys.is_down(KeyCode::KEY_ESCAPE))
Exiting the game doesn't belong with movement controls, it should be in a system together with Pause or other game states that controls the overall game flow.

2023-04-05 16:58 UTC, Mentathiel commented on src/Main.cpp
> +				movement.force.y = -movement.moveforce;
Add curly braces even on "one liners" everywhere in code, it's easier to modify later and less error-prone.

2023-04-06 17:43 UTC, milica-vucic approved these changes

2023-04-09 17:18 UTC, gavrilovmiroslav commented
@harry-cpp this build fail is somewhat weird, don't you think?

2023-04-09 17:34 UTC, Mentathiel approved these changes

2023-04-10 07:32 UTC, harry-cpp commented
> @harry-cpp this build fail is somewhat weird, don't you think?

The fork just needs to be resynced with main.

2023-04-10 10:45 UTC, gavrilovmiroslav approved these changes
Mostly merge changes, next time merge directly no need to wait

2023-04-10 11:44 UTC, merged