Finished background , platform and "camera"
gavrilovmiroslav/dagger-relic pull request #14
Opened 2023-04-05 13:38 UTC by DaniloMatic99

Finished background and platform, and also something that act like camera where player is fixed.

2023-04-09 17:14 UTC, gavrilovmiroslav requested changes, later dismissed

2023-04-09 17:14 UTC, gavrilovmiroslav commented on src/Main.cpp
> +					// if (keys.is_down(bindings.up))
Indentation is all over the place, please pay attention to this and match the rest of the engine.

2023-04-09 17:14 UTC, gavrilovmiroslav commented on src/Main.cpp
> +					else{
Braces always go onto their own line and are not additionally indented.

2023-04-09 17:14 UTC, gavrilovmiroslav commented on src/Main.cpp
> +						if(side == true)
Please don't check `x == true`, just check `x` if it's a boolean.

2023-04-09 17:14 UTC, gavrilovmiroslav commented on src/Main.cpp
> +				{
This whole method needs to be reindented carefully.

2023-04-09 17:14 UTC, gavrilovmiroslav commented on src/Rendering.cpp
> +#include <SDL2/SDL.h>
This should now be fixed and actually incorrect - pull from main and compile from meson and VSCode

2023-04-11 05:58 UTC, msimic01 approved these changes

2023-04-11 05:59 UTC, msimic01 approved these changes

2023-04-15 20:13 UTC, gavrilovmiroslav approved these changes
Generally you don't want to let your review to grow to this size, but let's do it! Chunkification is key!

2023-04-18 16:47 UTC, gavrilovmiroslav commented
Are we closing this, @DaniloMatic99 ?

2023-04-18 17:20 UTC, merged