Added parsing level and collecting coins
gavrilovmiroslav/dagger-relic pull request #28
Opened 2023-04-19 13:37 UTC by DaniloMatic99

Level is parsed throw file in data, where '*' describe place on screen where coin need to be placed. Also pick up is finished, and counting collected coins.

2023-04-21 11:21 UTC, M4444 requested changes

2023-04-21 11:21 UTC, M4444 commented on data/coin/goldCoin.png.data
> +scale: 1, 1
No new line at the end of file as GitHub also noted.
Integrating #30 and saving the files again should solve this.

2023-04-21 11:21 UTC, M4444 commented on src/Background.cpp
> +			if(counter < NUMBER_OF_BACKGROUND-2)
```suggestion
			if (counter < NUMBER_OF_BACKGROUND - 2)
```

2023-04-21 11:21 UTC, M4444 commented on src/Item.cpp
This file has a mix of tabs and spaces while tabs should be primary.
#30 will help fix the aliment and make this more obvious.

Also some unnecessary empty rows (e.g. line 5, 8, 26, etc).

2023-04-21 11:21 UTC, M4444 commented on src/Platform.cpp
> +#include <iostream>
Keep an empty row below the includes.

2023-04-21 11:28 UTC, M4444 commented on src/PlayerControls.cpp
Could these magic number be refactored out?

2023-04-24 08:37 UTC, pejovicnina approved these changes

2023-04-24 21:23 UTC, M4444 requested changes

2023-04-24 21:23 UTC, M4444 commented on data/coin/goldCoin.png.data
> +scale: 1, 1
This comment still applies.

2023-04-24 21:23 UTC, M4444 commented on include/Background.h
> +      public MutAccessUnique<OurGlobalVar>
These should also be tabs and commas at the start to make it consistent.
`class AssetModule` in `Assets.h` is a good example.

2023-04-24 21:23 UTC, M4444 commented on include/Item.h
> +      public MutAccessUnique<OurGlobalVar>
Same thing as in `Background.h`.

2023-04-24 21:23 UTC, M4444 commented on include/Platform.h
> +      public MutAccessUnique<OurGlobalVar>
And again here.

2023-04-24 21:23 UTC, M4444 commented on src/Main.cpp
> +      public AllocateUnique<OurGlobalVar>
Here too.

2023-04-24 22:04 UTC, M4444 approved these changes

2023-04-24 22:15 UTC, merged