refactor: Moved code of systems and components from Main to separate …
gavrilovmiroslav/dagger-relic pull request #3
Opened 2023-03-30 20:17 UTC by vladjov00

…files + modified gravity system

Main.cpp now includes GameSpecificComponents.h and GameSpecificSystems.h
- GameSpecificComponents.h: Contains definitions of constants and components with no behaviour
- GameSpecificSystems.h: Includes .h files of all non-Dagger Systems used for SWMG

Gravity now takes into account player's vertical velocity and updates it every tick, so which means that gravitational pull should feel more natural now.

2023-03-30 20:31 UTC, gavrilovmiroslav requested changes

2023-03-30 20:31 UTC, gavrilovmiroslav commented on include/GameSpecificComponents.h
> +	bool is_grounded;
Please use Definitions.h to be more specific about your types. This is useful as both an exercise for when you get a job in a big company and it has its own type-definitions, and as a real-world exercise in precision under stress. In these cases, rewrite this as `Bool`, `F32` and `F64` (for double). Below, there's `const char*` which is `LiteralString`. 

Pointers serve several functions in C++, so we want to be really specific about our intent: we can have a `RawPtr<T>` if we want a real pointer to something. We can use `SharedPtr` for shared ownership (most cases), `UniquePtr` for unique ownership, and `StaticArray<T, N>` to define a static array of type T and size N, a `DynamicArray<T>` to define a vector, and a `SmallBuffer<T>`  for when you know you have like... 10 elements; also `Ref<T>` for `T&`, and a lot of other things. All of this is in Definitions.h, use it often and get used to it!

2023-03-30 20:35 UTC, gavrilovmiroslav commented on include/GameSpecificComponents.h
> +	bool is_grounded;
Also, our code is written in the ANSI C++ style, and not the Kernighan & Ritchie style, meaning that `{}` go on their own separate lines.

2023-03-30 20:35 UTC, gavrilovmiroslav commented on include/Pickup.h
> +	using QueryPlayers 	= MutAccessGroupStorage<Player, Position>;
weird spacing, no need to align or anything like that, let your IDE do the hard work :)

2023-03-30 20:36 UTC, gavrilovmiroslav commented on src/Combat.cpp
> +    for(auto&& [attack_entity, attack, attack_pos, sprite, flip] : QueryAttacks :: access_storage().each()){
All the `{` go in their own line, make it more readable where the blocks start and end

2023-03-30 20:36 UTC, gavrilovmiroslav commented on src/Combat.cpp
> +    for(auto&& [attack_entity, attack, attack_pos, sprite, flip] : QueryAttacks :: access_storage().each()){
`QueryAttacks::access_storage()` goes without spaces, as does any `a.b`, `a::b` etc.

2023-03-30 20:37 UTC, gavrilovmiroslav commented on src/Combat.cpp
> +            if (	abs(player_pos.xy.x - attack_pos.xy.x) <= attack.radius
if you want to align these, i'd rather go for aligning with the start of the line but eh, it might be okay

2023-03-30 20:37 UTC, gavrilovmiroslav commented on src/Combat.cpp
> +            if (	abs(player_pos.xy.x - attack_pos.xy.x) <= attack.radius
whatever you choose, choose consistently!

2023-03-30 20:38 UTC, gavrilovmiroslav commented on src/Platform.cpp
> +            if(	player_pos.xy.x <= platform_pos.xy.x + platform.width / 2 + 11
I like this style a lot more, so please choose one and adhere to it!

2023-03-30 22:22 UTC, vladjov00 commented on include/GameSpecificComponents.h
> +#define SCREEN_WIDTH 800
I have no idea how the dagger.ini file works, how do other files see and use values defined there?

2023-03-31 17:15 UTC, jormundur00 reviewed
Good and very needed refactoring. Gravity files could maybe be renamed into PhysicSystems files, in case of a decision to expand on that system with more physics, but we will cross that bridge when we get there.

2023-03-31 17:20 UTC, jormundur00 approved these changes

2023-03-31 17:26 UTC, merged