Added boss
gavrilovmiroslav/dagger-relic pull request #34
Opened 2023-04-27 13:55 UTC by pejovicnina

Added boss on the end of level

2023-04-27 22:17 UTC, M4444 requested changes

2023-04-27 22:17 UTC, M4444 commented on include/GameSystem.h
> +#include "Monster.h"
No new line at the end of file.

2023-04-27 22:17 UTC, M4444 commented on src/Monster.cpp
> +			if (keys.is_down(bindings.up))
```suggestion
			std::cout << monster_pos.xy.x << "     " << monster_pos.xy.y << std::endl;

			if (keys.is_down(bindings.up))
```

2023-04-27 22:17 UTC, M4444 commented on src/Main.cpp
> +
Stray whitespace.

2023-05-04 09:33 UTC, DaniloMatic99 approved these changes

2023-05-04 09:40 UTC, DaniloMatic99 approved these changes

2023-05-04 10:52 UTC, M4444 approved these changes

2023-05-04 10:52 UTC, merged